// <auto-generated />
using System;
using ContratacaoService.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContratacaoService.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929042627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ContratacaoService.Domain.Contratacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContratadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
